### PR TITLE
Convert project to Typescript (2.1.0 update)

### LINKED ISSUE #2: new highlight not write correctly
I noticed the new highlight obfuscate option does not write 'correctly' as it uses the same writing code as the normal obfuscate https://github.com/ferib/lua-obfuscator-plugin/blob/master/extension.js#L278.

Is it possible to overwrite the selected highlighted text with the new obfuscated code instead?

### PR DESCRIPTION
**Pull request by kdssoftware**
I've been working on this over the weekend.
Converted the plugin to TypeScript, to package and transpile `vsce package`.
- fixed #2 
- Profiler feature has been removed.
- Lots of refactoring
- Removed the api key option in the settings, since its currently hardcoded

Please install the `.vsix` package and test this 👍

### CODE REVIEW

**Comment by ferib** [comment]
Awesome work! will have a look on Thursday

**Comment by ferib** [comment]
Something is incorrect with a fix on #2, I selected Lua and obfuscated using `Obfuscate current highlighted code` but the new code seems to overwrite the original code at position 0. The length of the code overwritten seems correct tho.

**Comment by kdssoftware** [comment]
Its fixed now 👌 , the `npm run compile` script was incorrect.

https://github.com/ferib/lua-obfuscator-plugin/assets/10829524/0efa7b49-40a1-4a6c-be51-7d2b505e6f7f

**Comment by ferib** [comment]
LGTM 🎉

**Pull request merged**
